# -*- coding: utf-8 -*-
"""Carabas_Images-Reading_exemple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKfGraQMLsPv9Un1GsL-Oto8WqP9_8Ex
"""

import os
import cv2

# 1. Configurações de acesso
REPO_URL = "https://github.com/steinbukken7321/CARABAS-II-SAR-Dataset-Mirror.git"
REPO_NAME = "CARABAS-II-SAR-Dataset-Mirror"
PATH_TO_IMG = f"{REPO_NAME}/img"

# 2. Clonagem do repositório
# Verifica se a pasta do repositório já existe para não clonar novamente
if not os.path.exists(REPO_NAME):
    print("Baixando repositório do GitHub...")
    os.system(f"git clone {REPO_URL}")

# 3. Verificação do diretório de imagens
if not os.path.exists(PATH_TO_IMG):
    print(f"Erro: A pasta {PATH_TO_IMG} não foi encontrada no repositório clonado.")
    # Lista o conteúdo para ajudar no diagnóstico
    if os.path.exists(REPO_NAME):
        print(f"Conteúdo do repositório: {os.listdir(REPO_NAME)}")
else:
    print(f"Pasta {PATH_TO_IMG} localizada com sucesso.")

# 4. Leitura das imagens
valid_extensions = ('.png', '.jpg', '.jpeg', '.tif', '.bmp', '.mat')
image_files = [f for f in os.listdir(PATH_TO_IMG) if f.lower().endswith(valid_extensions)]

print(f"Arquivos encontrados: {len(image_files)}")

carabas_images = []
for filename in image_files:
    full_path = os.path.join(PATH_TO_IMG, filename)
    img = cv2.imread(full_path, cv2.IMREAD_UNCHANGED)

    if img is not None:
        carabas_images.append(img)

print(f"Total de imagens carregadas na memória: {len(carabas_images)}")

import matplotlib.pyplot as plt

# Verificação se a lista contém imagens antes de tentar plotar
if len(carabas_images) > 0:
    print(f"Exibindo {len(carabas_images)} imagens do dataset CARABAS-II...")

    for i, img in enumerate(carabas_images):
        plt.figure(figsize=(8, 6))

        # Como são dados SAR, exibimos em escala de cinza (gray)
        # O Matplotlib ajusta automaticamente a escala de visualização para o range dos dados
        plt.imshow(img, cmap='gray')

        plt.title(f"Amostra SAR {i+1} - Resolução: {img.shape}")
        plt.axis('off')  # Oculta os eixos para melhor visualização
        plt.show()
else:
    print("Nenhuma imagem disponível para exibição. Verifique se o diretório contém arquivos válidos.")